image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install -g npm
      npm install 
      npm run build
      rm /tmp/.npm-lock
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      npm install -g .
      ifttt --help
